name: "LLM Reviewer"
author: "Pengfei Ni"
description: "Automated pull requests reviewing and issues triaging with ChatGPT"
inputs:
  GITHUB_TOKEN:
    description: "Github token used to send out review comments"
    required: true
  OPENAI_API_KEY:
    description: "API key used to invoke OpenAI"
    required: false
  OPENAI_API_BASE:
    description: "API based used to access [Azure] OpenAI API"
    required: false
  ANTHROPIC_API_KEY:
    description: "API key used to invoke Anthropic Claude"
    required: false
  model:
    description: "LLM model name"
    default: "claude-3-5-sonnet-20240620"
    required: false
  blocking:
    description: "Blocking the pull requests on LLM failures"
    default: 'False'
    required: false
  temperature:
    description: "Temperature for the model"
    default: '0.2'
    required: false
  review_per_file:
    description: "Send out review requests per file"
    default: 'False'
    required: false
  comment_per_file:
    description: "Post review comments per file"
    default: 'True'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --model=${{ inputs.model }}
  - --temperature=${{ inputs.temperature }}
  - --review-per-file=${{ inputs.review_per_file }}
  - --comment-per-file=${{ inputs.comment_per_file }}
  - --blocking=${{ inputs.blocking }}
branding:
  icon: 'compass'
  color: 'blue'
